
/****** Object:  Database [winform]    Script Date: 5/14/2020 2:14:16 PM ******/
CREATE DATABASE [winform]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'winform', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\winform.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'winform_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\winform_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [winform] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [winform].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [winform] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [winform] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [winform] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [winform] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [winform] SET ARITHABORT OFF 
GO
ALTER DATABASE [winform] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [winform] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [winform] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [winform] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [winform] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [winform] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [winform] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [winform] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [winform] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [winform] SET  ENABLE_BROKER 
GO
ALTER DATABASE [winform] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [winform] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [winform] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [winform] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [winform] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [winform] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [winform] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [winform] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [winform] SET  MULTI_USER 
GO
ALTER DATABASE [winform] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [winform] SET DB_CHAINING OFF 
GO
ALTER DATABASE [winform] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [winform] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [winform]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 5/14/2020 2:14:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[login]    Script Date: 5/14/2020 2:14:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 5/14/2020 2:14:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[price] [decimal](6, 2) NOT NULL,
	[CategoryId] [int] NULL,
	[ProductsDescription] [varchar](50) NULL,
	[UnitsInStock] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([CategoryId])
GO
USE [master]
GO
ALTER DATABASE [winform] SET  READ_WRITE 
GO
